default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: rumbrain_development

test:
  <<: *default
  database: rumbrain_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  cable:
    <<: *default
    database: rumbrain_test
  queue:
    <<: *default
    database: rumbrain_test
  cache:
    <<: *default
    database: rumbrain_test


production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    prepared_statements: false

  queue:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    prepared_statements: false

  cache:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    prepared_statements: false